version: '3.9'
services:
  proxy:
    image: 1234567890.dkr.ecr.ap-northeast-1.amazonaws.com/wordpress-docker-proxy
    container_name: wp-proxy
    ports:
      - 8888:80
    environment:
      - UPSTREAM_HOST=127.0.0.1
    command: >
      /bin/sh -c
      "envsubst '$$UPSTREAM_HOST'
      < /etc/nginx/conf.d/default.conf.template
      > /etc/nginx/conf.d/default.conf
      && nginx -g 'daemon off;'""
    volumes:
      - ./app:/usr/share/nginx/html
      - ./docker/nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
  app:
    image: 1234567890.dkr.ecr.ap-northeast-1.amazonaws.com/wordpress-docker-app
    container_name: wp-app
    environment:
      - USE_SSL=on
      - DB_NAME=wordpress
      - DB_USER=wordpress
      - DB_PASSWORD=wordpress
      - DB_HOST=db
    volumes:
      - ./app:/var/www/html